name: venv
channels:
  - conda-forge
#- nodefaults  # this will fail if packages missing in conda-forge
dependencies:
  - python=3.7
  - pip=20.1.1
  - wheel=0.35
  - psutil=5.7
  - shap=0.34
  - numpy=1.18
  - scipy=1.4
  - joblib=0.14
  - scikit-learn=0.22
  - scikit-image=0.16
  - matplotlib=3.3
  - pandas=0.25
  - numba=0.51
  - pyarrow=1.0.1
  - ipywidgets=7.5
  - jsonpickle=1.4
  - jmespath=0.10
  - click=7.1
  - statsmodels=0.10
  - isodate=0.6
  - protobuf=3.13
  - ruamel.yaml=0.16
  - fire=0.3
  - flask=1.1
  - flask-cors=3.0
  - gevent=20.9
  - cython=0.29
  - pyjwt=1.7
  - boto=2.49
  - boto3=1.16
  - botocore=1.19
  - tqdm=4.42
  - py-xgboost=0.90
  - fbprophet=0.6
  - pytest=6.1
  - black=20.8b1
  - python-json-logger=2.0
  - pytest-mock=3.4
  - pyjwt=1.7
  - pip:
    - azureml-sdk==1.16.0
    - azureml-defaults==1.16.0
    - azureml-interpret==1.16.0
    - azureml-opendatasets==1.16.0
    - azureml-train-automl==1.16.0
    - azureml-widgets==1.16.0
    - inference-schema==1.1.0
    - onnx==1.7.0

