version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/fermium"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/app:cached
    command: jupyter notebook --ip=0.0.0.0 --port=8888
