name: train
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip=21.0
  - numpy=1.18
  - scipy=1.4
  - joblib=0.14
  - scikit-learn=0.22
  - pandas=0.25
  - pyarrow=1.0.1
  - idna=2.10
  - py-xgboost=0.90
  - pyjwt=1.7
  - python-json-logger=2.0
  - pip:
      - azureml-sdk==1.23.0
      - azureml-defaults==1.23.0
      - azureml-interpret==1.23.0
      - azureml-train-automl==1.23.0
      - azureml-widgets==1.23.0
      - inference-schema==1.1.0
      - onnx==1.7.0
