name: main

env:
  AZ_CLI_VERSION: 2.18.0
  AZ_CLI_ML_VERSION: 1.21.0

on:
  push:

jobs:
  main:
    name: main
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: sudo apt-get update && sudo apt-get install -y python3-virtualenv
        run: sudo apt-get update && sudo apt-get install -y python3-virtualenv

      - name: virtualenv venv --python=python3
        run: virtualenv venv --python=python3

      - name: . venv/bin/activate&& pip install -r .github/workflows/requirements.txt
        run: . venv/bin/activate&& pip install -r .github/workflows/requirements.txt

      - name: . venv/bin/activate&& pylint ./nd00333 || pylint-exit $?
        run: . venv/bin/activate&& pylint ./nd00333 || pylint-exit $?

      - name: . venv/bin/activate&& pylint ./tests || pylint-exit $?
        run: . venv/bin/activate&& pylint ./tests || pylint-exit $?

      - name: install az-cli
        shell: bash
        run: |
          curl -sO https://packages.microsoft.com/repos/azure-cli/pool/main/a/azure-cli/azure-cli_2.18.0-1~focal_all.deb \
          && sudo dpkg -i azure-cli_*.deb \
          && az --version \
          && rm -f azure-cli_*.deb

      - name: az version --query '"azure-cli"' | grep ${{ env.AZ_CLI_VERSION }}
        run: az version --query '"azure-cli"' | grep ${{ env.AZ_CLI_VERSION }}

      - name: install az-cli-ml
        run: az extension add --name azure-cli-ml --version ${{ env.AZ_CLI_ML_VERSION }} --debug

      - name: az version --query '"extensions"."azure-cli-ml"' | grep ${{ env.AZ_CLI_ML_VERSION }}
        run: az version --query '"extensions"."azure-cli-ml"' | grep ${{ env.AZ_CLI_ML_VERSION }}

      - name: az --version
        run: az --version

      - uses: azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: download the ids2018test_1 dataset onto datasets/ids2018test
        shell: bash
        run: |
          az ml datastore download --workspace-name nd00333-capstone --resource-group nd00333-capstone \
          --name workspaceblobstore --prefix ids2018test_1 --target-path . --verbose
          mv ids2018test_1 datasets/ids2018test

      - name: . venv/bin/activate&& python -m pytest -v
        run: . venv/bin/activate&& python -m pytest -v

      - name: aml_workspace
        id: aml_workspace
        uses: Azure/aml-workspace@cdf55f1e593b02923a1a33f468c410f1fd6da818
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: aml_compute
        id: aml_compute
        uses: Azure/aml-compute@0bafcdd641d5c307037bd4bea82d303f17787541
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: echo $CONFIG_JSON > config.json
        run: echo $CONFIG_JSON > config.json
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}

      - name: aml_run
        id: aml_run
        uses: Azure/aml-run@e1efa559107a525e0ef78dd3beb38464b60cf749
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
        env:
          REPOSITORY_ROOT: "/github/workspace"

      - name: aml_registermodel
        id: aml_registermodel
        uses: Azure/aml-registermodel@b630dde3715e43d48664e536a0af1c2fefee1b0a
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          run_id: ${{ steps.aml_run.outputs.run_id }}
          experiment_name: ${{ steps.aml_run.outputs.experiment_name }}

      - name: aml_deploy
        id: aml_deploy
        uses: Azure/aml-deploy@28bd9f37ba5e967a2fcfdee3b04e4f11c5dbfbd4
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          model_name: ${{ steps.aml_registermodel.outputs.model_name }}
          model_version: ${{ steps.aml_registermodel.outputs.model_version }}
